// Generated by https://quicktype.io

export interface Product {
    idProduct:   number;
    productName: string;
    unitPrice:   number;
    stock:       number;
    status:      number;
    category:    Category | null;
}

export interface Category {
    idCategory:   number;
    categoryName: string;
    status:       number;
}
